version: "3.8"

services:
  # db:
  #   image: mongo:latest
  #   container_name: db
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - db-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: pass

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:pass@db:27017
  #   depends_on:
  #     - "db"

  # scraper:
  #   build:
  #     context: ./scraper_service
  #   environment:
  #     MONGO_URI: mongodb://admin:pass@db:27017
  #     MONGO_DATABASE: scraper
  #     RMQ_HOST: rbmq
  #     RMQ_PORT: 5672
  #     RMQ_QUEUE: ""
  #     RMQ_EXCHANGE: "articles"
  #     RMQ_ROUTING_KEY: "scraped.articles"
  #   restart: unless-stopped
  #   depends_on:
  #     - "db"
  #     - "rbmq"

  # rbmq:
  #   image: rabbitmq:3
  #   container_name: rbmq
  #   volumes:
  #     - rbmq-data:/var/lib/rabbitmq

  # summarization:
  #   build:
  #     context: ./summarization_service
  #   environment:
  #     RMQ_HOST: rbmq
  #     RMQ_PORT: 5672
  #     MONGO_URI: mongodb+srv://ms1514094:ngNcu4DZmmup4fYl@cluster0.v5584ym.mongodb.net
  #     MONGO_DB: summary
  #   restart: always
  #   depends_on:
  #     - "db"
  #     - "rbmq"

  summary-api:
    build: ./summary_service
    environment:
      MONGO_URI: mongodb+srv://ms1514094:ngNcu4DZmmup4fYl@cluster0.v5584ym.mongodb.net/
      MONGO_DB: summary
    ports:
      - 3000:3000
    volumes:
      - ./summary_service:/app
      - node_modules:/app/node_modules
    restart: always

volumes:
  node_modules:
  db-data:
  rbmq-data:
