version: "3.8"

services:
  scraper-db:
    image: mongo:latest
    container_name: scraper-db
    restart: unless-stopped
    volumes:
      - scraper-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@scraper-db:27017
    depends_on:
      - "scraper-db"

  scraper:
    build:
      context: ./scraper_service
    environment:
      MONGO_URI: mongodb://root:root@scraper-db:27017
      MONGO_DATABASE: scraper
      RMQ_HOST: rbmq
      RMQ_PORT: 5672
      RMQ_QUEUE: ""
      RMQ_EXCHANGE: "articles"
      RMQ_ROUTING_KEY: "scraped.articles"
    restart: unless-stopped
    depends_on:
      - "scraper-db"
      - "rbmq"

  rbmq:
    image: rabbitmq:3
    container_name: rbmq
    volumes:
      - rbmq-data:/var/lib/rabbitmq

  summarization:
    build:
      context: ./summarization_service
    environment:
      RMQ_HOST: rbmq
      RMQ_PORT: 5672
      RMQ_QUEUE: ""
      RMQ_EXCHANGE: "articles"
      RMQ_ROUTING_KEY: "scraped.articles"
    restart: always
    depends_on:
      - "rbmq"
volumes:
  scraper-data:
  rbmq-data:
