version: '3.8'

services:
  
  # scraper-db:
  #   image: mongo:latest
  #   container_name: scraper-db
  #   restart: unless-stopped
  #   # volumes not needed for now
  #   # volumes:
  #     # - scraper-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@summary-api-db:27017
    depends_on:
      - "summary-api-db"
  
   
  # scraper:
  #   build:
  #     context: ./scraper_service
  #   environment:
  #     - MONGO_URI=mongodb://root:root@scraper-db:27017
  #     - MONGO_DATABASE=scraper
  #   restart: unless-stopped
  #   depends_on:
  #     - "scraper-db"

  summary-api-db:
    image: mongo:latest
    container_name: summary-api-db
    restart: unless-stopped
    # volumes not needed for now
    # volumes:
      # - scraper-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  summary-api:
    build: ./summary_service
    environment:
      MONGO_URI: mongodb://root:root@summary-api-db:27017
    ports:
      - "3000:3000"
    depends_on:
      - "summary-api-db"

